version: '3'
services:
  web: # Ruby on Railsが起動するコンテナ
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "./start.sh"]
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
    volumes:
      - .:/jphacks2020 # アプリケーションファイルの同期
    depends_on:
      - db
    # command: ["./start.sh"]
    # command: ["rails", "server", "-b", "0.0.0.0"]
  db: # MySQLが起動するコンテナ
    image: mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql # データの永続化
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'jphacks2020_development'
volumes:
  mysql_data: # データボリュームの登録