name: ci

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: gem Install Prettier
        run: |
          gem install prettier
        working-directory: ./backend

      - name: Install Prettier
        run: |
          npm install -g prettier

      - name: Install Prettier Plugin
        run: |
          npm install --save-dev prettier @prettier/plugin-ruby
        working-directory: ./backend

      - name: Run Prettier For Frontend
        run: |
          prettier --write "src/**/*.{css,html,js}"
        working-directory: ./frontend

      - name: Run Prettier For Backend
        run: |
          ./node_modules/.bin/prettier --write '**/*.rb'
        working-directory: ./backend

      - name: Commit format
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format